expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from receipts.views import ReceiptRedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", ReceiptRedirectView.as_view()),
   
]

receipts/urls.py
from django.urls import path
from receipts.views import ReceiptView


urlpatterns = [
    path("", ReceiptView.as_view(), name="home")
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        ExpenseCategory,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )

accounts/views.py
from django.shortcuts import render

# Create your views here.

receipts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView

from receipts.models import Receipt
from django.views.generic.base import RedirectView


class ReceiptView(ListView):
    model = Receipt
    template_name = "receipts_list.html"


class ReceiptRedirectView(RedirectView):
    url = "/receipts/"
    pattern_name = "home"

receipts/templates/receipts_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
    </head>
    <body>
        <header>
        </header>
        <main>
            <h1>My Receipts</h1>
            <table>
                <thead>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </thead>
                <tbody>
                    {%for receipt in receipt_list%}
                    <tr>
                        <td>{{receipt.vendor}}</td>
                        <td>{{receipt.total}}</td>
                        <td>{{receipt.tax}}</td>
                        <td>{{receipt.date| date:"m/d/YY" }}</td>
                        <td>{{receipt.category}}</td>
                        <td>{{receipt.account}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>